myproject/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from django.contrib.auth import views as auth_views
from myapp import views
from django.views.generic import TemplateView
from django.conf.urls.static import static
from django.conf import settings

admin.autodiscover()

urlpatterns = [
    # url('^api/auth/', include('social_django.urls', namespace='social')),
    
    url(r'^results2/$',views.buy_search,name="buy_search"),
    url(r'^results1/$',views.sell_search,name="sell_search"),
    url(r'^addzone/(?P<id>[0-9]+)/$',views.addzone, name='zone'),
    url(r'^addround/(?P<id>[0-9]+)/$', views.addround, name='addround'),
    url(r'^addticket/(?P<id>[0-9]+)/$', views.addticket, name='addticket'),
    path('addconcert/', views.CreateConcertView.as_view(), name='addconcert'),
    path('oauth/', include('social_django.urls', namespace='social')), # in django2
    url(r'^login/$', auth_views.login, name='login'), 
    path('logout/',views.logout, name='logout'),   
    path('admin/', admin.site.urls),    
    path('home/', views.home, name='home'),
    path('sell/', views.sell, name='sell'),
    path('buy/', views.buy, name='buy'),
    url(r'^choosezone/(?P<id>[0-9]+)/$', views.choosezone, name='choosezone'),
    url(r'^ticket/(?P<id>[0-9]+)/$', views.ticket, name='ticket'),
    url(r'^contact/(?P<id>[0-9]+)/$', views.contact, name='contact'),
    path('accounts/', include('django.contrib.auth.urls')),
    url(r'^order/(?P<id>[0-9]+)/(?P<shipping>[0-9]+)/$', views.CreateOrder ,name="order"),
    path('editprofile/', views.update_profile, name='editprofile'),
    path('profile/', views.profile, name='profile'),
    url(r'^profile/(?P<id>[0-9]+)/$', views.view_profile, name='profile'),
    url(r'^soldout/(?P<id>[0-9]+)/$', views.change_soldout, name='soldout'),
    url(r'^onsell/(?P<id>[0-9]+)/$', views.change_onsell, name='onsell'),
    url(r'changetoread/(?P<id>[0-9]+)/$', views.changetoread, name='changetoread'),
    path('contactus/', views.contactus,name='contactus'),
    url(r'^vieworder/(?P<id>[0-9]+)/$', views.view_order, name='vieworder'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myapp/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from myapp.choice import *
from django.contrib.auth.signals import user_logged_in


def do_stuff(sender, user, request, **kwargs):
    if not Customer.objects.filter(user=user).exists():
        customer = Customer.objects.create(user=user)

user_logged_in.connect(do_stuff)

class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE,default='')
    #email = models.EmailField(unique=True)
    #user_name = models.CharField(unique=True,max_length=15,blank=True)
    #first_name = models.CharField(max_length=30, blank=True)
    #last_name = models.CharField(max_length=30, blank=True)
    profile_pic = models.ImageField(default='images/usersymbol.png',upload_to='images/',null=True)
    num_phone = models.CharField(max_length=30,blank=True, null=True)
    bank_name = models.CharField(max_length=30)
    account_number = models.CharField(max_length=30)

class Ticket(models.Model):
    no = models.CharField(unique=True,blank=True,max_length=6,default=0)
    row = models.CharField(default=0,max_length=3)
    seat = models.IntegerField(blank=True)
    price = models.IntegerField(default=0)
    pic = models.ImageField(upload_to='images/')
    status = models.CharField(default="ON SELL",max_length=20)
    customer = models.ForeignKey('Customer', on_delete=models.CASCADE)
    zone = models.ForeignKey('Zone',on_delete=models.CASCADE,default=0)

class Round(models.Model):
    date = models.DateField(blank=True,null=True)
    start = models.TimeField(blank=True,null=True)
    concert = models.ForeignKey('Concert',on_delete=models.CASCADE,default=0)
    def __str__(self):
        return self.concert.name +" | Date : "+ str(self.date) +" | Start : "+ str(self.start)

class Concert(models.Model):
    name = models.CharField(max_length=120)
    place = models.CharField(max_length=120)
    concert_pic = models.ImageField(upload_to='images/', null=True, blank=True)
    concert_picplan = models.ImageField(upload_to='images/', null=True, blank=True)
    def __str__(self):
        return self.name

class Zone(models.Model):
    name = models.CharField(max_length=10,blank=True)
    round = models.ForeignKey('Round',on_delete=models.CASCADE,default=0)
    def __str__(self):
        return "Zone: "+ self.name
        
class Order(models.Model):
    shipment = models.IntegerField(choices=STATUS_CHOICE,default=1)
    date = models.DateTimeField(blank=True,null=True)
    ticket = models.ForeignKey('Ticket',on_delete=models.CASCADE,default=0)
    status = models.CharField(max_length = 30,default="unread")
    buyer = models.ForeignKey(User, on_delete=models.CASCADE)
    slip = models.ImageField(upload_to='images/', blank=True, null=True)
    address = models.CharField(max_length = 300,blank=False)

myapp/views.py
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.views.generic.edit import CreateView
from django.views.generic.list import ListView
from django.views.generic import UpdateView
from django.conf import settings
from django.contrib.auth.models import User
from .models import Ticket,Concert,Customer,Round,Zone,Order
from .forms import TicketForm,ConcertForm,CustomerForm,RoundForm,ZoneForm,OrderForm,UserForm
from django.db.models import Q
import datetime
from django.utils import timezone

def home(request):
    concert = Concert.objects.all()
    ticket = Ticket.objects.all()
    order = Order.objects.all()
    customer = Customer.objects.all()
    context = {
        'concert':concert,
        'ticket' : ticket,
        'order' : order,
        'customer' : customer,
    }
    return render(request, 'home.html' , context)

def logout(request):
    success_url = '/login'
    return render(request, 'https://api.tu.ac.th/logout/')

def addround(request,id):
    formset = RoundForm()
    con = Concert.objects.get(id=id)
    order = Order.objects.all()
    # con = Concert.objects.all()
    round = Round.objects.get(id=id)
    # con_concert.id=str(con_concert.id)
    if request.method == 'GET':
        formset = RoundForm(initial={'concert':con})
        return render(request, 'addround.html',{'formset':formset,'con':con,'order' : order})
    elif request.method == 'POST':
        formset = RoundForm(request.POST, request.FILES)
        if formset.is_valid():
            obj = Round.objects.create(**formset.cleaned_data)
            obj.save()
            return redirect('/sell')
        else:
            return render(request, 'home.html')
    else:
        return render(request, 'addround.html',{'formset':formset,'order' : order})

def addticket(request,id):
    formset = TicketForm()
    customer = Customer.objects.get(user = request.user)
    round = Round.objects.get(id=id)
    zone = Zone.objects.filter(round= round)
    if request.method == 'GET':
        formset = TicketForm(initial={'customer':customer})
        return render(request, 'addticket.html',{'formset':formset,'con':round.concert,'order' : order,'round':round})
    if request.method == 'POST':
        formset = TicketForm(request.POST, request.FILES)
        if formset.is_valid():
            obj = Ticket.objects.create(**formset.cleaned_data)
            obj.save()
            return redirect('/sell')
        else:
            return render(request, 'home.html', {'formset':formset,'order' : order})
    else:
        return render(request, 'addticket.html',{'formset':formset,'order' : order})

def addconcert(request):
    form = ConcertForm()
    order = Order.objects.all()
    context = {
        'form' : form,
        'order' : order,
    }
    if request.method == 'POST':
        print("sell")
        return redirect('/sell')
    else:
        print("addcon")
        return render(request, 'addconcert.html',context)

def sell(request):
    order = Order.objects.all()
    concert = Concert.objects.all()
    ticket = Ticket.objects.all()
    day = Round.objects.all()
    order = Order.objects.all()
    context = {
        'concert':concert,
        'ticket' : ticket,
        'day' : day,
        'order' : order,
    }
    return render(request, 'sell.html' , context)

def sell_search(request):
    template = 'sell.html'
    day = Round.objects.all()
    order = Order.objects.all()
    query = request.GET.get('q')
    if query:
        results1 = Concert.objects.filter(Q(name=query))
    else:
        concert = Concert.objects.all()
    context = {
        'results1':results1,
        'ticket' : ticket,
        'day' : day,
        'order' : order,
    }
    return render(request, template, context)

def buy(request):
    concert = Concert.objects.all()
    order = Order.objects.all()
    concert = Concert.objects.all()
    day = Round.objects.all()
    context = {
        'concert':concert,
        'ticket' : ticket,
        'day' : day,
        'order' : order,
    }
    return render(request, 'buy.html' , context)

def buy_search(request):
    template = 'buy.html'
    order = Order.objects.all()
    day = Round.objects.all()
    query = request.GET.get('q')
    if query:
        results2 = Concert.objects.filter(Q(name=query))
    else:
        concert = Concert.objects.all()
    context = {
        'results2':results2,
        'ticket' : ticket,
        'day' : day,
        'order' : order,
    }
    return render(request, template, context)

def choosezone(request,id):
    #concert = Concert.objects.all()
    #ticket = Ticket.objects.all()
    r = Round.objects.get(id=id)
    order = Order.objects.all()
    zone = Zone.objects.filter(round_id=id)
    context = {
        'zone' : zone,
        'r' : r,
        'order' : order,
    }
    return render(request, 'choosezone.html', context)

def ticket(request,id):
    zone_object = Zone.objects.get(id=id)
    ticket = Ticket.objects.filter(zone_id=id)
    order = Order.objects.all()
    return render(request, 'ticket.html',{'ticket' : ticket,'zone_object' : zone_object,'order' : order})

def contact(request,id):
    order = Order.objects.all()
    ticket = Ticket.objects.get(id=id)
    customer = Customer.objects.get(id=ticket.customer.id)
    return render(request, 'contact.html',{'ticket' : ticket,'customer' : customer,'order' : order})

def contactus(request):
    concert = Concert.objects.all()
    ticket = Ticket.objects.all()
    order = Order.objects.all()
    customer = Customer.objects.all()
    context = {
        'concert':concert,
        'ticket' : ticket,
        'order' : order,
        'customer' : customer,
    }
    return render(request, 'contactus.html', context)

def order(request):
    return render(request, 'order.html')

class CreateTicketView(CreateView):
    queryset = Ticket()
    template_name='addticket.html'
    form_class = TicketForm
    success_url = '/ticket'

class CreateConcertView(CreateView):
    queryset = Concert()
    template_name='addconcert.html'
    form_class = ConcertForm
    success_url = '/sell'

class CreateCustomerView(CreateView):
    queryset = Customer()
    form_class = CustomerForm
    success_url = '/admin'


class CreateRoundView(CreateView):
    queryset = Round()
    template_name='addround.html'
    form_class = RoundForm
    success_url = '/sell'

def CreateOrder(request,id,shipping):
    formset=OrderForm()
    ticket = Ticket.objects.get(id=id)
    zone_id = str(ticket.zone_id)
    if shipping == '1':
        total = ticket.price+30
    else :
        total = ticket.price+50
    if request.method == 'GET':
        formset = OrderForm(initial={'buyer':request.user,'ticket':ticket,'status':"unread",'shipment':shipping,'date': (timezone.make_aware(datetime.datetime.now(),timezone.get_default_timezone()))})
        return render(request, 'order.html',{'formset':formset,'ticket':ticket,'shipping':shipping,'total':total})
    elif request.method == 'POST' :
        formset = OrderForm(request.POST, request.FILES)
        if formset.is_valid():
            print("yes")
            obj = Order.objects.create(**formset.cleaned_data)
            obj.save()
            ticket.status = "WAITING CONFIRM";
            ticket.save()
            return redirect('/ticket/'+zone_id)
        else:
            return render(request, 'home.html')
    else:
        return render(request, 'order.html',{'formset':formset,'order' : order,})

        
class UpdateOrder(UpdateView):
    queryset = Order.objects.all()
    template_name = 'order.html'
    form_class = OrderForm
    success_url = '/'

class CreateZonetView(CreateView):
    queryset = Zone()
    template_name='addzone.html'
    form_class = ZoneForm
    success_url = '/sell'

def profile(request):
    return render(request, 'profile.html')



def addzone(request,id):
    formset = ZoneForm()
    round = Round.objects.get(id=id)
    if request.method == 'GET':
        formset = ZoneForm(initial={'round':round})
        return render(request, 'addzone.html',{'formset':formset,'round':round})
    elif request.method == 'POST' :
        formset = ZoneForm(request.POST, request.FILES)
        if formset.is_valid():
            print("yes")
            obj = Zone.objects.create(**formset.cleaned_data)
            obj.save()
            return redirect('/addticket/'+id)
        else:
            return render(request, 'home.html')
    else:
        return render(request, 'addzone.html',{'formset':formset,'round':round})

def view_profile(request,id):
    ticket = Ticket.objects.filter(customer=id)
    user = User.objects.get(id=id)
    return render(request, 'profile.html',{'ticket' : ticket})

def update_profile(request):
    if request.method == 'POST':
        user_form = UserForm(request.POST, instance=request.user)
        customer_form = CustomerForm(request.POST, request.FILES, instance=request.user.customer)
        # print(request.POST)
        # print(request.FILES)
        if user_form.is_valid() and customer_form.is_valid():

            # print('valid')
            user_form.save()
            customer_form.save()
            # messages.success(request, _('Your profile was successfully updated!'))
            return redirect('profile', id=request.user.customer.id)
        # else:
        #     messages.error(request, _('Please correct the error below.'))
    else:
        user_form = UserForm(instance=request.user)
        customer_form = CustomerForm(instance=request.user.customer)
    return render(request, 'edit_profile.html', {
        'user_form': user_form,
        'customer_form': customer_form
    })

def changetoread(request,id):
    order = Order.objects.get(id = id)
    order.status = "read"
    order.save()

    return redirect('profile',id=request.user.customer.id)

def change_soldout(request,id):

myapp/templates/addconcert.html
 <!DOCTYPE html>
<html>
<style type="text/css">
	body{
		padding: 0; 
		margin: 0;
		font-family: 'Poppins', sans-serif;
		background-image: url("/static/images/bg.jpg");
	}

	.error{
		background-color: #e85959;
		color: white;
		text-align: center;
		width: 100%;
		float: clear;
		padding-top: 0.3%;
		padding-bottom: 0.3%;
	}
	.menu{
		width: 100%;
		height: 70px;
		background-color: white;
		box-shadow: 0px 2px 10px 0px rgba(0, 0, 0, 0.65);
		float: left;
	}

	.menutitle{
  		text-align: center ;
  		margin: 23px 0;
  		
	}

	.logo{
  		margin-left: 5%;
  		background-color: transparent;
  		float: left;

	}

	.but{
		background-color: transparent;
  		text-align: center ;
  		
	}
	
	.aa a{
	    color: #e85959;
	    text-decoration: none;
    	text-align: center;
  		display: inline-block;
  		padding-left: 2%;
  		padding-right: 2%;
  		float: right;
  		font-size: 22px;
	}

	.ab a{  		
	    color: #e85959;
	    text-decoration: none;
  		display: inline-block;
  		padding-left: 2%;
  		padding-right: -0.2%;
  		margin-top: -12px;
  		float: right;

	}

	.aab a{
		border-right: 2px solid #a1a1a1;
		height: 25px;
 		color: #e85959;
	    text-decoration: none;
    	text-align: center;
  		display: inline-block;
  		padding-left: 2%;
  		padding-right: 2%;
  		float: right;
  		font-size: 22px;

	}
	/*-----------------------------------------------------*/


.titleCon{
  font-family: 'Poppins', sans-serif;
  text-align: center;
  color: #e85959;
  margin-top:8%;
  margin-bottom:3%;
  font-size: 220%;

 }

.box1{
	float: left;
}

.box1 label{
	color: white;
	font-size: 25px;
	display: flex;
	padding-bottom: 11%;
}

.box2{
	
	width: 100%;
	padding-left: 25%;
	font-size: 20px;

	margin: auto;
}

.box2 input{
	color: #e85959 ;   
}


.b1 {
	padding-bottom: 2%;
}

.b2 {
	padding-bottom: 3%;
}

.b3 {	
	padding-bottom: 3%;
}


.group {
	width: 70%;
	padding: 4%;
	margin: auto;
	border-radius: 20px;
	background-color: rgba(107, 103, 102, 0.4);
}

.custom-file-upload {
   	font-size: 23px;
    border-radius: 8px;
	color: #e85959 ;   
	padding: 6px 30px;
    cursor: pointer;
    background-color: white;
}

input[type="file"] {
    display: none;
}

.forb{
	width: 100%;
	font-family: 'Poppins', sans-serif;
	padding-top: 5%;
	margin: auto;
	padding-left: 43%;

}
/*ปุ่ม*/
.button { 
    background-color: #e85959;
    border: none;
    color: white;
    padding: 12px 25px;
    text-align: center;
    text-decoration: none;
    display: inline-block;
    font-size: 25px;
    cursor: pointer;
    border-radius: 8px;
}

 			/* width */
	::-webkit-scrollbar {
	    width: 15px;
	}

	
	/* Track */
	::-webkit-scrollbar-track {
	    background: #e85959; 

	}
	 
	/* Handle */
	::-webkit-scrollbar-thumb {
	    background: #9b2828; 
	    border-radius: 8px;
	}

	/* Handle on hover */
	::-webkit-scrollbar-thumb:hover {
	    background: #721414; 
	}

.myNotification {
	position: absolute;
    bottom: 92.5%;
   	right: 7.2%;
    font-size: 15px;
    background-color: red;
   	border-radius: 50%;
	border: solid red; 
	border-right: 9px solid red;
	border-left: 9px solid red;
	color: white;
	width: 0.4%;
}
.usersymbolContainer{
	text-align: top;
	background-color: red;
	cursor: pointer;
}
</style>
<head>
	<title>Add Concert</title>
	<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
</head>
<body>

	{% load staticfiles %} 
	{% if request.user.is_authenticated %}
	<div class = "error">
		Please verify seller's information and be careful of second-handed ticket selling online before purchasing 
	</div>


	<div class="menu">
		<div class="logo">
  			<a href='/home' target= "_blank"><img src="{% static "images/reticlogo.png" %}" width="160" height="70"></a>
		</div>
		<div class="menutitle">
			<div class="aa"><a href="{% url 'logout'%}" target="_blank">Logout</a></div>			
			<div class="usersymbolContainer">		
					<div class="ab"><a href='/profile/{{user.id}}' target= "_blank">

					{% if user.customer.profile_pic == "" %}
						<img src="{% static "images/usersymbol.png" %}" width="50" height="50" style="border-radius:50%" id="idImg">	
					{% else %}
						<img src="{{user.customer.profile_pic.url}}" width="50" height="50" style="border-radius:50%" id="idImg">
					{% endif %}
					</a>	  
					</div>

					{% for order in order %}
						{% if user.username  == order.ticket.customer.user.username %}
							{% if order.status  == "unread" %}
								<div class="myNotification" 
							> ! </div>
							{% endif %}
							{% if order.status  == "read" %}
								<div class="myNotification" 
								style="display:none;"> ! </div>
							{% endif %}
						{% endif %}
					{% endfor %}
				</div>	

			<div class="aab"><a href="/home" target="_blank">Contact</a></div>

			<div class="aa"><a href="/sell" target="_blank">Seller</a></div>			
			<div class="aa"><a href="/buy" target="_blank">Buyer</a></div>
		</div>
	</div>

	
	<!-- ............................................................................................................................... -->


	<div class="titleCon"><h1>Add concert</h1></div>

	<div class="group">
		{% block content %}
			<form method="post" enctype="multipart/form-data">
				{% csrf_token %}
				<div class="mybox">
					<div class="box1">
						<label style="padding-top: 5%;">Name: </label>
						<label>Place: </label>
						<label>Concert Image: </label>
						<label>Diagram Image: </label>	
					</div>
					
					<div class="box2">
						<div class="b1">
							<input size="20" class="w3-input w3-border w3-round-large" 
							type="text" name="name" class="forms-control" required="" 
							id="id_name" value="" style="text-align: right;"> 
						</div>
						<div class="b2">
							<input size="20" class="w3-input w3-border w3-round-large" 
							type="text" name="place" class="forms-control" required="" id="id_place" value="" style="text-align: right;"> 
						</div>
						<div class="b3">
							<label class="custom-file-upload">
	    						{{form.concert_pic}}
							</label>
						</div>

						<div class="b4">
							<label class="custom-file-upload">
	    						{{form.concert_picplan}}
							</label>
						</div>

					</div>
				</div>
					
				<div class="forb">
					<input type="submit" class="button" name="buyticket" value=" Submit " />
				</div>
			</form>
			{% endblock %}
	</div>
	{% else %}
       	<div class="myContainer1">  
	        <div class="myContainer2">
	            <div class="myLogo">
	                <img src="{% static "images/reticlogo.png" %}" width="400" height="200">
	            </div>
	            <div class="myLogin">
	                <a href="{% url 'social:begin' 'tu' %}">Login with TU</a>
	            </div>
	        </div>
    	</div>
    {% endif %}
</body>
</html>

myapp/templates/home.html
<!DOCTYPE html>
<html>
<style type="text/css">
body{
	padding: 0;
	margin: 0;
	font-family: 'Poppins', sans-serif;
	background-image: url("/static/images/bg.jpg");	
}
.myLogin a{
    text-decoration: none;
    color: #e85959;
    font-size: 40px;
}
.myLogin {
    text-align: center;
    align-items: center;
    padding-left: 50px;
}
.myLogo img{
    border-right: 3px solid #a1a1a1;
}
.myLogo {
  	margin: 0px;
}
.myContainer1 {
    align-items: center;
    margin: auto;
    position: relative;
    padding-top: 13%;
}
.myContainer2 {
    position: absolute;
    margin: auto;
    display: flex;
    align-items: center;
    padding-left: 30%;
}

.myContainer3 a{
    text-decoration: none;
    color: #e85959;
    text-align: center;
}
.myContainer3{
	 margin-top: 1%;
     padding-left: 93%;
}
@media(max-width: 600px){
    .aa a{
	}
}
.error{
	background-color: #e85959;
	color: white;
	text-align: center;
	width: 100%;
	float: clear;
	padding-top: 0.3%;
	padding-bottom: 0.3%;
}
.menu{
	width: 100%;
	height: 70px;
	background-color: white;
	box-shadow: 0px 2px 10px 0px rgba(0, 0, 0, 0.65);
	float: left;
}
.menutitle{
  	text-align: center ;
  	margin: 23px 0;
}
.logo{
  	margin-left: 5%;
  	background-color: transparent;
  	float: left;
}
.but{
	background-color: transparent;
  	text-align: center ;
}	
.aa a{
	color: #e85959;
	text-decoration: none;
    text-align: center;
  	display: inline-block;
  	padding-left: 2%;
  	padding-right: 2%;
  	float: right;
  	font-size: 22px;
}
.ab a{  		
	color: #e85959;
	text-decoration: none;
  	display: inline-block;
  	padding-left: 2%;
  	padding-right: -0.2%;
  	margin-top: -12px;
  	float: right;
}
.aab a{
	border-right: 2px solid #a1a1a1;
	height: 25px;
 	color: #e85959;
	text-decoration: none;
    text-align: center;
  	display: inline-block;
  	padding-left: 2%;
  	padding-right: 2%;
  	float: right;
  	font-size: 22px;
}
.coverbut{
	float: left;
	width: 26%;
	height: 26%;
	margin-right:5%;
	margin-left:5%;
}
.coverbut p{
	font-size: 400%;
	color: #a1a1a1;
	text-align: center;
}
.coverbut img{
 	opacity: 0.9;
    filter: alpha(opacity=30); 	
}
.content{
	margin-top: 8%;
	margin-right:0;
	margin-left:20%;
}
#content{
	margin: 0 center;
}
.myNotification {
	position: absolute;
    bottom: 92.5%;
   	right: 7.2%;
    font-size: 15px;
    background-color: red;
   	border-radius: 50%;
	border: solid red; 
	border-right: 9px solid red;
	border-left: 9px solid red;
	color: white;
	width: 0.4%;
}
.usersymbolContainer{
	text-align: top;
	background-color: red;
	cursor: pointer;
}
@media(max-width: 600px){
	.aa a{
	}
}
</style>
<head>
<title>Home</title>
</head>
<body>
	{% load staticfiles %}
	{% if request.user.is_authenticated %}
		<div class = "error">
			Please verify seller's information and be careful of second-handed ticket selling online before purchasing 
		</div>
		<div class="menu">
			<div class="logo">
	  			<a href='/home' target= "_blank"><img src="{% static "images/reticlogo.png" %}" width="160" height="70"></a>
			</div>
			<div class="menutitle">
				<div class="aa"><a href="{% url 'logout'%}" target="">Logout</a></div>			
				<div class="usersymbolContainer">		
					<div class="ab"><a href='/profile/{{user.id}}' target= "_blank">

					{% if user.customer.profile_pic == "" %}
						<img src="{% static "images/usersymbol.png" %}" width="50" height="50" style="border-radius:50%" id="idImg">	
					{% else %}
						<img src="{{user.customer.profile_pic.url}}" width="50" height="50" style="border-radius:50%" id="idImg">
					{% endif %}
					</a>	  
					</div>

					{% for order in order %}
						{% if user.username  == order.ticket.customer.user.username %}
							{% if order.status  == "unread" %}
								<div class="myNotification" 
							> ! </div>
							{% endif %}
							{% if order.status  == "read" %}
								<div class="myNotification" 
								style="display:none;"> ! </div>
							{% endif %}
						{% endif %}
					{% endfor %}
				</div>	
				<div class="aab"><a href="/contactus" target="_blank">Contact</a></div>
				<div class="aa"><a href="/sell" target="_blank">Seller</a></div>			
				<div class="aa"><a href="/buy" target="_blank">Buyer</a></div>
			</div>
		</div>
		<div class="content" id="content">	
			<div class="coverbut">
				<p>BUYER</p><a href='/buy' target= "_blank"><img src="{% static "images/buylogo.png" %}" width= "100%" height="100%"></a>
		  	</div>
		  	<div class="coverbut">
				<p>SELLER</p><a href='/sell' target= "_blank"><img src="{% static "images/reselllogo.png" %}" width= "100%" height="100%"></a>
		  	</div>
		</div>
	{% else %}
       	<div class="myContainer1">  
	        <div class="myContainer2">
	            <div class="myLogo">
	                <img src="{% static "images/reticlogo.png" %}" width="400" height="200">
	            </div>
	            <div class="myLogin">
	                <a href="{% url 'social:begin' 'tu' %}">Login with TU</a>
	            </div>
	        </div>
    	</div>
    {% endif %}
<script>
	function myFunc(e){
		alert(e);
	}
</script>
</body>
</html> 